/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as StayIndexRouteImport } from './routes/stay.index'
import { Route as StaySlugRouteImport } from './routes/stay.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StayIndexRoute = StayIndexRouteImport.update({
  id: '/stay/',
  path: '/stay/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaySlugRoute = StaySlugRouteImport.update({
  id: '/stay/$slug',
  path: '/stay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/weddings': typeof WeddingsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/stay/$slug': typeof StaySlugRoute
  '/stay/': typeof StayIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/weddings': typeof WeddingsRoute
  '/stay/$slug': typeof StaySlugRoute
  '/stay': typeof StayIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/weddings': typeof WeddingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/stay/$slug': typeof StaySlugRoute
  '/stay/': typeof StayIndexRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/offers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/weddings'
    | '/admin'
    | '/stay/$slug'
    | '/stay/'
    | '/admin/enquiries'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/offers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/weddings'
    | '/stay/$slug'
    | '/stay'
    | '/admin/enquiries'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/dining'
    | '/experiences'
    | '/gallery'
    | '/offers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/weddings'
    | '/_authenticated/admin'
    | '/stay/$slug'
    | '/stay/'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WeddingsRoute: typeof WeddingsRoute
  StaySlugRoute: typeof StaySlugRoute
  StayIndexRoute: typeof StayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/stay/': {
      id: '/stay/'
      path: '/stay'
      fullPath: '/stay/'
      preLoaderRoute: typeof StayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/$slug': {
      id: '/stay/$slug'
      path: '/stay/$slug'
      fullPath: '/stay/$slug'
      preLoaderRoute: typeof StaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WeddingsRoute: WeddingsRoute,
  StaySlugRoute: StaySlugRoute,
  StayIndexRoute: StayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
